# Generated by Django 3.2 on 2021-04-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('datePosted', models.DateTimeField()),
                ('dateDue', models.DateTimeField()),
                ('numHelperRequested', models.IntegerField()),
                ('taskDuration', models.DurationField()),
                ('contributors', models.ManyToManyField(related_name='job_contributors', to='oddjob.User')),
                ('originUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_originUser', to='oddjob.user')),
                ('tags', models.ManyToManyField(to='oddjob.Tag')),
            ],
        ),
    ]
