# Generated by Django 3.2 on 2021-04-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oddjob', '0003_alter_job_originuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='oddjob.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='dateDue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='datePosted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='numHelperRequested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='originUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originUser', to='oddjob.user'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='oddjob.Tag'),
        ),
        migrations.AlterField(
            model_name='job',
            name='taskDuration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
