# Generated by Django 3.2 on 2021-04-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddjob', '0004_auto_20210409_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
